#!/usr/bin/env bash

set -eu -o pipefail

function run() {
	local test=$1

	echo $test

	local test_args="$(cat $test/args)"

	set +e
	$semvercmp_path \
		$test_args \
		2>&1 \
		>|$test/actual

	echo "Exit code: $?" >>$test/actual
	set -e

	diff $test/expected $test/actual
}

semvercmp_path="../target/debug/semvercmp"
if [[ $# > 0 && $1 == "--release" ]]; then
	lbdt_path="../target/release/semvercmp"
	shift
fi

if [[ $# == 0 ]]; then
	for dir in $(find . -mindepth 1 -type d | sort); do
		run $dir
	done
else
	for dir in $@; do
		run $dir
	done
fi
